Algoritmo "Exe01"
//
//
// Descrição   : Você digita dois números na tela e será contado os números de um número inicial a um número final
// Autor(a)    : Giulia Santana Silva
// Data atual  : 16/08/2021
Var
// Seção de Declarações das variáveis 
cont,inicial,final:inteiro

Inicio
escreval("Digite o valor inicial: ")
leia(inicial)
escreval("Digite o valor final: ")
leia(final)

para cont de inicial ate final faca
   escreval("cont => ", cont)
fimpara

Fimalgoritmo