Algoritmo "EXE6"
// 
//  
// Descrição   : Quando dado 10 números inteiros, ao final é apresentado a soma de todos os números juntos
// Autor(a)    : Giulia Santana Silva
// Data atual  : 17/08/2021
Var
// Seção de Declarações das variáveis 
x,n,soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para n<- ate 10 faca
 escreval("Entre com o valor")
 leia(x)
 soma<-soma+x
fimpara
escreval("Resultado", soma)


Fimalgoritmo